### ISSUE TITLE
Group is misnamed and fields don't import

### ISSUE THREAD

**Issue by greenhodge** [iamntz/acf-recovery#2]
Thanks for making this! I'm sorry to say that it didn't work for me. I'm using ACF 5.4.8. The only thing I can figure out is that the post_type for the group should be acf-field-group (not "acf"), but I can't easily see why the fields aren't importing at all. Are you interested in updating this tool?

**Comment by iamntz** [comment]
Hey man, unfortunately, this was build for ACF 4. 

I'll try to see if i can make it work with ACF 5 as well, but don't expect any wonders anytime soon.

**Comment by greenhodge** [comment]
Hey IMNTZ - I found this one and it works: https://github.com/BeAPI/ACF-PHP-Recovery You might want to update the readme for your tool to specify that it doesn't work for ACF 5, and direct people to the other one. Thanks!
